### PR TITLE
[fix] su cave modify 数据访问错误

### PR DESCRIPTION
**Pull request by xxtg666**

### CODE REVIEW

**Comment by XieXiLin3** [comment]
**This branch has conflicts that must be resolved.**

**Conflicting files**
`src/plugins/Core/plugins/su.py`

**Comment by xxtg666** [comment]
pr就不用加完成标签了，那个是给issue用的

**Comment by xxtg666** [comment]
算了，加了就加了吧

**Comment by XieXiLin3** [comment]
6

**Pull request merged**
